-- Euro Zyn Products
INSERT INTO products (id, name, category, strength, stock, multipleOf, status) VALUES
('euro-0', 'Mini Cool Mint', 'Euro Zyn Flavours', '3mg', 200, 5, 'In Stock'),
('euro-1', 'Black Cherry', 'Euro Zyn Flavours', '6mg', 70, 5, 'In Stock'),
('euro-2', 'Mini Espressino', 'Euro Zyn Flavours', '6mg', 199, 5, 'In Stock'),
('euro-3', 'Lemon Spritz', 'Euro Zyn Flavours', '6.5mg', 65, 5, 'In Stock'),
('euro-4', 'Gentle Mint', 'Euro Zyn Flavours', '6.5mg', 350, 5, 'In Stock'),
('euro-5', 'Cucumber Lime', 'Euro Zyn Flavours', '6.5mg', 90, 5, 'In Stock'),
('euro-6', 'Citrus', 'Euro Zyn Flavours', '9mg', 40, 5, 'In Stock'),
('euro-7', 'Apple Mint', 'Euro Zyn Flavours', '9mg', 90, 5, 'In Stock'),
('euro-8', 'Spearmint', 'Euro Zyn Flavours', '9mg', 115, 5, 'In Stock'),
('euro-9', 'Cool Frost', 'Euro Zyn Flavours', '9mg', 240, 5, 'In Stock'),
('euro-10', 'Banana Milkshake', 'Euro Zyn Flavours', '9mg', 150, 5, 'In Stock'),
('euro-11', 'Exotic Mango', 'Euro Zyn Flavours', '9mg', 110, 5, 'In Stock'),
('euro-12', 'Black Cherry', 'Euro Zyn Flavours', '9mg', 90, 5, 'In Stock'),
('euro-13', 'Pineapple Coconut', 'Euro Zyn Flavours', '9mg', 180, 5, 'In Stock'),
('euro-14', 'Purple Chill', 'Euro Zyn Flavours', '9mg', 200, 5, 'In Stock'),
('euro-15', 'Honeydew', 'Euro Zyn Flavours', '9mg', 215, 5, 'In Stock'),
('euro-16', 'Fizzy Cola', 'Euro Zyn Flavours', '9mg', 110, 5, 'In Stock'),
('euro-17', 'Peach Bellini', 'Euro Zyn Flavours', '9mg', 55, 5, 'In Stock'),
('euro-18', 'Cherry Cola', 'Euro Zyn Flavours', '9mg', 210, 5, 'In Stock'),
('euro-19', 'Red Fruits', 'Euro Zyn Flavours', '9mg', 200, 5, 'In Stock'),
('euro-20', 'Icy Blue Razz', 'Euro Zyn Flavours', '9mg', 105, 5, 'In Stock'),
('euro-21', 'Straw Nana', 'Euro Zyn Flavours', '9mg', 195, 5, 'In Stock'),
('euro-22', 'Spearmint (New)', 'Euro Zyn Flavours', '9mg', 40, 5, 'In Stock'),
('euro-23', 'Citrus', 'Euro Zyn Flavours', '11mg', 90, 5, 'In Stock'),
('euro-24', 'Apple Mint', 'Euro Zyn Flavours', '11mg', 110, 5, 'In Stock'),
('euro-25', 'Deep Freeze', 'Euro Zyn Flavours', '11mg', 150, 5, 'In Stock'),
('euro-26', 'Sour Ruby', 'Euro Zyn Flavours', '11mg', 90, 5, 'In Stock'),
('euro-27', 'Cool Watermelon', 'Euro Zyn Flavours', '11mg', 150, 5, 'In Stock'),
('euro-28', 'Cool Mint', 'Euro Zyn Flavours', '11mg', 70, 5, 'In Stock'),
('euro-29', 'Cool Blueberry', 'Euro Zyn Flavours', '11mg', 60, 5, 'In Stock'),
('euro-30', 'Cool Tropical', 'Euro Zyn Flavours', '11mg', 125, 5, 'In Stock'),
('euro-31', 'Gummy Bear (New)', 'Euro Zyn Flavours', '11mg', 250, 5, 'In Stock'),
('euro-32', 'Pink Lemon', 'Euro Zyn Flavours', '11mg', 280, 5, 'In Stock'),
('euro-33', 'Citrus Mint', 'Euro Zyn Flavours', '11mg', 90, 5, 'In Stock'),
('euro-34', 'Skittles', 'Euro Zyn Flavours', '11mg', 220, 5, 'In Stock'),
('euro-35', 'Icy Blackcurrant', 'Euro Zyn Flavours', '12.5mg', 160, 5, 'In Stock'),
('euro-36', 'Icy Mint', 'Euro Zyn Flavours', '12.5mg', 70, 5, 'In Stock'),
('euro-37', 'Wintergreen', 'Euro Zyn Flavours', '15mg', 220, 5, 'In Stock'),
('euro-38', 'Cool Mint', 'Euro Zyn Flavours', '16.6mg', 30, 5, 'In Stock');

-- American Zyn Products
INSERT INTO products (id, name, category, strength, stock, multipleOf, status) VALUES
('american-0', 'Cool Mint', 'American Zyn Flavours', '3mg', 150, 5, 'In Stock'),
('american-1', 'Citrus', 'American Zyn Flavours', '3mg', 100, 5, 'In Stock'),
('american-2', 'Coffee', 'American Zyn Flavours', '3mg', 100, 5, 'In Stock'),
('american-3', 'Wintergreen', 'American Zyn Flavours', '3mg', 100, 5, 'In Stock'),
('american-4', 'Spearmint', 'American Zyn Flavours', '3mg', 150, 5, 'In Stock'),
('american-5', 'Cool Mint', 'American Zyn Flavours', '6mg', 140, 5, 'In Stock'),
('american-6', 'Citrus', 'American Zyn Flavours', '6mg', 40, 5, 'In Stock'),
('american-7', 'Coffee', 'American Zyn Flavours', '6mg', 100, 5, 'In Stock'),
('american-8', 'Menthol', 'American Zyn Flavours', '6mg', 200, 5, 'In Stock'),
('american-9', 'Wintergreen', 'American Zyn Flavours', '6mg', 75, 5, 'In Stock'),
('american-10', 'Cinnamon', 'American Zyn Flavours', '6mg', 100, 5, 'In Stock'),
('american-11', 'Peppermint', 'American Zyn Flavours', '6mg', 100, 5, 'In Stock'),
('american-12', 'Redbull', 'American Zyn Flavours', '6mg', 30, 5, 'In Stock'),
('american-13', 'White Monster', 'American Zyn Flavours', '6mg', 10, 5, 'Low Stock'),
('american-14', 'Strawberry Monster', 'American Zyn Flavours', '6mg', 0, 5, 'Out of Stock');

-- VELO Products
INSERT INTO products (id, name, category, strength, stock, multipleOf, status) VALUES
('velo-0', 'Frosty Grapefruit', 'VELO Flavour', '10mg', 140, 10, 'In Stock'),
('velo-1', 'Lime Flame', 'VELO Flavour', '10mg', 120, 10, 'In Stock'),
('velo-2', 'Icy Berries', 'VELO Flavour', '10mg', 140, 10, 'In Stock'),
('velo-3', 'Peppermint Storm', 'VELO Flavour', '10.9mg', 170, 10, 'In Stock'),
('velo-4', 'Polar Mint', 'VELO Flavour', '11mg', 150, 10, 'In Stock'),
('velo-5', 'Freeze', 'VELO Flavour', '11mg', 180, 10, 'In Stock'),
('velo-6', 'Witty Spearmint', 'VELO Flavour', '11mg', 170, 10, 'In Stock'),
('velo-7', 'Breezy Mango', 'VELO Flavour', '11mg', 170, 10, 'In Stock'),
('velo-8', 'Cool Storm', 'VELO Flavour', '11mg', 160, 10, 'In Stock'),
('velo-9', 'Icy Cherry', 'VELO Flavour', '12mg', 150, 10, 'In Stock'),
('velo-10', 'Groovy Grape', 'VELO Flavour', '12mg', 140, 10, 'In Stock'),
('velo-11', 'Polar Mint', 'VELO Flavour', '14mg', 160, 10, 'In Stock'),
('velo-12', 'Ruby Berry', 'VELO Flavour', '14mg', 110, 10, 'In Stock'),
('velo-13', 'Orange Spark', 'VELO Flavour', '14mg', 99, 10, 'In Stock'),
('velo-14', 'Max Freeze', 'VELO Flavour', '17mg', 180, 10, 'In Stock'),
('velo-15', 'Mighty Peppermint', 'VELO Flavour', '17mg', 150, 10, 'In Stock'),
('velo-16', 'X-Freeze', 'VELO Flavour', '20mg', 130, 10, 'In Stock');

-- Whitefox Products
INSERT INTO products (id, name, category, strength, stock, multipleOf, status) VALUES
('whitefox-0', 'Peppermint', 'Whitefox Flavour', '12mg', 159, 10, 'In Stock'),
('whitefox-1', 'Double Mint', 'Whitefox Flavour', '12mg', 360, 10, 'In Stock'),
('whitefox-2', 'Original', 'Whitefox Flavour', '12mg', 330, 10, 'In Stock'),
('whitefox-3', 'Full Charge', 'Whitefox Flavour', '16mg', 350, 10, 'In Stock'),
('whitefox-4', 'Black Mint', 'Whitefox Flavour', '22.5mg', 180, 10, 'In Stock');
